### ISSUE TITLE
SurvivalGame - Todo's / Updates

### ISSUE THREAD

**Issue by xZeroMCPE** [AndreTheGamer/SurvivalGame#82]
**You will get a quick preview at what the lastest release does here:**

**Version: 1.0.10**   (Just got submited today) 
- [x] Better messages
- [x] You are now able to setup arena, and restart it will work
- [x] It will display when a player dies, Such as `Player: max Dies`
- [x] Multiple bugs fixed `Death, chests,,ect)`
- [x] Better sign format ;) 

On the future release versions, Economy won't be required. So that way it"ll be better for you guys. It will be like a choice to have it :) 

**# Todos**
- [ ] Support dynamic number of players
- [ ] Ability to set **multiple** arena
- [ ] Automaticity  chest reset
- [ ] Full message config, allows you to edit arenas message :)
- [ ] Built-In ranks system such as for `VIPs`
- [ ] If you have an suggestions? Create a issue :) ,
- [ ] 15 seconds god mod, When match first started

I'll also make sure these list are updated, If you have a suggestions or questions go head and create a issue report. But if its just a simple questions you may use this issue and reply below. My goal for SurvivalGame is to be 100% Bug free. If you are wanting to contribute go head and fork my project and create a pull request. Although make sure you do test the changed you've made, and make sure you have a very good codding structure.

**Comment by CLiu13** [comment]
Sweet, can't wait to see auto-chest-reset added! :)

Also, are you going to add the god-mode thing?

**Comment by xZeroMCPE** [comment]
Yea, i am.

**Comment by xZeroMCPE** [comment]
There should be a release today, But a few things has been changed so **Multiple** arena support and migrating to it can be easy :) 

Again, there isn't a release yet but i"ll give you guys some info about it :)

What changed?
- Setting up arena has changed to **/sg setup arena <#>**
- Reloading settings for arena has changed to **/sg reload arena <#>**
- Starting a arena (Force starting) is now **/sg start arena <#>**
- Removing settings is now **/sg remove arena <#>**

Features addded?
- You will be able to add chest on which gets reset use **/sg setup chest**
- To finishe adding a chest use **/sg setup chest done**

Please be aware that features such as chest is still in beta and multiple arena suppost, Although you are able to setup arena number 1.  As of now there are some testings being done. If you have any suggestions tell us below :)
