### ISSUE TITLE
[TODO for New-Release]

### ISSUE THREAD

**Issue by xZeroMCPE** [AndreTheGamer/SurvivalGame#91]
**TODO**
# 

We are working on a new release, Which will support multiple arenas, ability to customized message and pick a lang file
- [x] language file? (ENG As default)
- [ ] Multiple arenas
- [ ] Auto chest refill
- [ ] Blocked words,commands (during game)

**Comment by xZeroMCPE** [comment]
Multi lang is completed :) i will be working on a few more things i've stated above!

**Comment by ghost** [comment]
You're in ImagicalMine right?

**Comment by xZeroMCPE** [comment]
@imjayl  Yea

**Comment by ghost** [comment]
Do you know where can i get 14.1 phar version?
Btw . can i help with your project ?

**Comment by xZeroMCPE** [comment]
@imjayl  Create pull request to help out. and you can get a phar versioni of imagicalmine through there jenkins... Just look for there old builds.

**Comment by Intel1999** [comment]
I found that there was an error while reading the language file. I hope you fix them

**Comment by Intel1999** [comment]
I hope you can support Genisys-ITXtech.

**Comment by Intel1999** [comment]
Because the number of people who use it may be more than the core of the ClearSky

**Comment by xZeroMCPE** [comment]
@Intel1999 Somehow it gives a few errors while reading the lang file. But again i'm trying my best to fix :+1:

**Comment by xZeroMCPE** [comment]
Just updated the readme.md will try my best co complete this plugin!
